#端口
server:
  port: 8080
#  servlet:
#    context-path: /boot


#自定义的属性，指定了一个路径，注意要以/结尾
#D:/ls_web/upload/目录下的文件可以直接通过"http://localhost:8080/2.JPEG"的形式访问
system-params:
  upload-path: D:/ls_web/upload/

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ls_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database-platform: com.zcj.ls.ls_web.utils.CustomMysqlDialect
    hibernate:
    #update:第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），
    #以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。
        ddl-auto: update
  #页面缓存
  thymeleaf:
    cache: false
  mvc:
    #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:${system-params.upload-path}

#
#
#  web.upload-path=D:/temp/study13/
#  spring.mvc.static-path-pattern=/**
#  spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,\
#    classpath:/static/,classpath:/public/,file:${web.upload-path}