#端口
server:
  port: 18080
#  servlet:
#    context-path: /camera


#自定义的属性，指定了一个路径，注意要以/结尾
system-params:
#  图片上传保存路径
  upload-path: C:/ls_web/upload/
#  登录养老平台
  yl-login: http://61.153.190.75:8081/WorkManage/interface/APP/userLogin.action
#  获取服务大类列表
  yl-getServiceCategory: http://61.153.190.75:8081/WorkManage/interface/APP/getServiceCategory.action
#  获取服务项目列表
  yl-getServiceItem: http://61.153.190.75:8081/WorkManage/interface/APP/getServiceItem.action
#  提交订单
  yl-commitOrder: http://61.153.190.75:8081/WorkManage/interface/APP/commitOrder.action
#  订单查询
  yl-queryOrders: http://61.153.190.75:8081/WorkManage/interface/APP/queryOrders.action
#   取消订单
  yl-cancelOrder: http://61.153.190.75:8081/WorkManage/interface/APP/cancelOrder.action
#   萤石appKey
  camera-appKey: f5a87379c1eb47edb4b018c6527f157e
#   萤石appSecret
  camera-appSecret: 0169919196cdbbb10b888f2ee04b06f8
#   获取萤石token
  camera-getToken: https://open.ys7.com/api/lapp/token/get
#   添加设备
  camera-addDevice: https://open.ys7.com/api/lapp/device/add
#   修改设备名
  camera-deviceNameUpdate: https://open.ys7.com/api/lapp/device/name/update
#   关闭视频加密
  camera-deviceEncryptOff: https://open.ys7.com/api/lapp/device/encrypt/off
#   开通直播功能
  camera-liveVideoOpen: https://open.ys7.com/api/lapp/live/video/open
#   获取直播地址
  camera-getLiveAddress: https://open.ys7.com/api/lapp/live/address/get
#   关闭直播功能
  camera-liveVideoClose: https://open.ys7.com/api/lapp/live/video/close



#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ls_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    url: jdbc:mysql://180.101.143.121:3306/ls_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database-platform: com.zcj.ls.ls_web.utils.CustomMysqlDialect
    hibernate:
    #update:第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），
    #以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。
        ddl-auto: update
  #页面缓存
  thymeleaf:
    cache: true
  mvc:
    #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
  #项目static文件夹和file:${system-params.upload-path}目录下的文件可以直接通过"http://localhost:8080/2.JPEG"的形式访问
  resources:
    static-locations: classpath:/static/,file:${system-params.upload-path}